mc/mc/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mc.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', include('home.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^mi_cooperativa/', include('cooperatives.urls')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),
    )

mc/cooperatives/models.py
from django.db import models

class Organization(models.Model):
    nombre = models.CharField(max_length=200)
    siglas = models.CharField(max_length=200)
    domicilio = models.CharField(max_length=200)
    codigo_postal = models.CharField(max_length=200)
    ciudad = models.CharField(max_length=200)
    provincia = models.CharField(max_length=200)
    prefijo = models.IntegerField()
    telefonos = models.CharField(max_length=200)
    fax = models.CharField(max_length=200, null=True, blank=True)
    correo_electronico = models.CharField(max_length=200, null=True, blank=True) 
    director = models.CharField(max_length=200)
    director2 = models.CharField(max_length=200, null=True)

    def __unicode__(self):
        return self.provincia

class Cooperative(models.Model):
    provincia = models.ForeignKey(Organization)
    nombre = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=200, null=True, blank=True)
    objeto = models.CharField(max_length=200, null=True, blank=True)
    direccion = models.CharField(max_length=200, null=True, blank=True)
    localidad = models.CharField(max_length=200, null=True, blank=True)
    codigo_postal = models.CharField(max_length=200, null=True, blank=True)
    pub_date = models.DateTimeField('date published')
    capital_fecha = models.DateTimeField('date', null=True, blank=True)
    capital_monto = models.CharField(max_length=200, null=True, blank=True)
    capital_numero = models.CharField(max_length=200, null=True, blank=True)
    capital_banco = models.CharField(max_length=200, null=True, blank=True)
    capital_direccion = models.CharField(max_length=200, null=True, blank=True)
    presentacion = models.DateTimeField('date', null=True, blank=True)
    expediente = models.CharField(max_length=200, null=True, blank=True)
    matricula = models.CharField(max_length=200, null=True, blank=True)
    cuit = models.CharField(max_length=200, null=True, blank=True)

    def __unicode__(self):
        return self.nombre

class Partner(models.Model):
    cooperative = models.ForeignKey(Cooperative)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    correo_electronico = models.CharField(max_length=200)
    direccion = models.CharField(max_length=200)
    localidad = models.CharField(max_length=200)
    dni = models.IntegerField(default=0)
    fecha_de_nacimiento = models.DateTimeField('date')
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def __unicode__(self):
        return self.nombre

class Course(models.Model):
    partner = models.ForeignKey(Partner)
    fecha_de_asistencia = models.DateTimeField('date')
    sede = models.CharField(max_length=200)
    confirmacion = models.NullBooleanField()
    pub_date = models.DateTimeField('date published')

class Assembly(models.Model):
    cooperative = models.ForeignKey(Cooperative)
    fecha_de_convocatoria = models.DateTimeField('date')
    notificacion = models.NullBooleanField()
    direccion = models.CharField(max_length=200)
    localidad = models.CharField(max_length=200)
    codigo_postal = models.CharField(max_length=200)
    fecha_inicio_asamblea = models.DateTimeField('date')
    fecha_fin_asamblea = models.DateTimeField('date')
    precide_asamblea = models.OneToOneField(Partner, related_name='precide')
    miembros_consejo_1 = models.OneToOneField(Partner, related_name='consejo_1')
    miembros_consejo_2 = models.OneToOneField(Partner, related_name='consejo_2')
    miembros_consejo_3 = models.OneToOneField(Partner, related_name='consejo_3')
    sindico_titular = models.OneToOneField(Partner, related_name='sindico')
    sindico_suplente = models.OneToOneField(Partner, related_name='suplente')
    fecha_inicio_consejo = models.DateTimeField('date')
    fecha_fin_consejo = models.DateTimeField('date')
    miembros_consejo_presidente = models.OneToOneField(Partner, related_name='consejo_presidente')
    miembros_consejo_secretario = models.OneToOneField(Partner, related_name='consejo_secretario')
    miembros_consejo_tesorero = models.OneToOneField(Partner, related_name='consejo_tesorero')

mc/templates/mi_cooperativa/acta_consejo.html
{% extends "mi_cooperativa/base.html" %}
{% block inter %}
<section id="form_acta-consejo">
  <div class="content">
    <div class="help boxes-inaes">
      <div class="box box-acta-consejo active">
        <h5>Primer acta del consejo</h5>
        <h6>Distribución de cargos</h6><p>En este mismo acto, se realiza la Asamblea
Constitutiva y el estatuto de la cooperadora.</p>
<p>Es necesario que se encuentren todos los socios.</p>
<p>Al finalizar la asamblea, se debe imprimir y firmar por 
todos los socios.</p>
<p><a href="http://www.inaes.com.ar">Más información</a> </p>

      </div>
    </div>
    <div class="panel">
      <form action="{% url 'index' %}">
        <h3>01. Inicio de la reunión del consejo de administración</h3>
        <p>
          <label for="hora_inicio">Hora de inicio</label>
          <input type="date" id="hora_inicio" name="hora_inicio"/>
        </p>
        <hr>
        <h3>02. Elección de cargos</h3>
        <p>Se deben distribuir los cargos</p>
        <h5>Presidente</h5>
        <p>
          <input type="checkbox" id="socios_curso_Ariel Federico Asus" name="Ariel Federico Asus" value="Ariel Federico Asus"/>
          <label for="socios_curso_Ariel Federico Asus">Ariel Federico Asus</label>
          <input type="checkbox" id="socios_curso_Ariel Ramirez" name="Ariel Ramirez" value="Ariel Ramirez"/>
          <label for="socios_curso_Ariel Ramirez">Ariel Ramirez</label>
          <input type="checkbox" id="socios_curso_Jorge Ibañez" name="Jorge Ibañez" value="Jorge Ibañez"/>
          <label for="socios_curso_Jorge Ibañez">Jorge Ibañez</label>
        </p>
        <h5>Secretario</h5>
        <p>
          <input type="checkbox" id="socios_curso_Ariel Federico Asus" name="Ariel Federico Asus" value="Ariel Federico Asus"/>
          <label for="socios_curso_Ariel Federico Asus">Ariel Federico Asus</label>
          <input type="checkbox" id="socios_curso_Ariel Ramirez" name="Ariel Ramirez" value="Ariel Ramirez"/>
          <label for="socios_curso_Ariel Ramirez">Ariel Ramirez</label>
          <input type="checkbox" id="socios_curso_Jorge Ibañez" name="Jorge Ibañez" value="Jorge Ibañez"/>
          <label for="socios_curso_Jorge Ibañez">Jorge Ibañez</label>
        </p>
        <h5>Tesorero</h5>
        <p>
          <input type="checkbox" id="socios_curso_Ariel Federico Asus" name="Ariel Federico Asus" value="Ariel Federico Asus"/>
          <label for="socios_curso_Ariel Federico Asus">Ariel Federico Asus</label>
          <input type="checkbox" id="socios_curso_Ariel Ramirez" name="Ariel Ramirez" value="Ariel Ramirez"/>
          <label for="socios_curso_Ariel Ramirez">Ariel Ramirez</label>
          <input type="checkbox" id="socios_curso_Jorge Ibañez" name="Jorge Ibañez" value="Jorge Ibañez"/>
          <label for="socios_curso_Jorge Ibañez">Jorge Ibañez</label>
        </p>
        <hr>
        <h3>05. Finalización de la reunión del consejo de administración</h3>
        <p>
          <label for="hora_inicio">Hora de cierre</label>
          <input type="date" id="hora_inicio" name="hora_inicio"/>
        </p>
        <button>Finalizar</button><a href="{% url 'index' %}" class="volver">volver</a>
        <p><a href="#" class="descargar">Descargar acta</a></p>
      </form>
    </div>
  </div>
</section>
{% endblock %}

mc/templates/mi_cooperativa/asamblea.html
{% extends "mi_cooperativa/base.html" %}
{% block inter %}
<section id="form_asamblea">
  <div class="content">
    <div class="help boxes-inaes">
      <div class="box box-asamblea active">
        <h5>Asamblea Constitutiva</h5>
        <h6>Creación del estatuto</h6><p>En este mismo acto, se realiza la Asamblea
Constitutiva y el estatuto de la cooperadora.</p>
<p>Es necesario que se encuentren todos los socios.</p>
<p>Al finalizar la asamblea, se debe imprimir y firmar por 
todos los socios.</p>
<p><a href="http://www.inaes.com.ar">Más información</a> </p>

      </div>
    </div>
    <div class="panel">
      <form action="{% url 'index' %}">
        <h3>01. Inicio de asamblea interactiva</h3>
        <p>
          <label for="hora_inicio">Hora de inicio</label>
          <input type="date" id="hora_inicio" name="hora_inicio"/>
        </p>
        <hr>
        <h3>02. Elección de cargos para presidir la asamblea</h3>
        <p>
          <input type="checkbox" id="socios_curso_Ariel Federico Asus" name="Ariel Federico Asus" value="Ariel Federico Asus"/>
          <label for="socios_curso_Ariel Federico Asus">Ariel Federico Asus</label>
          <input type="checkbox" id="socios_curso_Ariel Ramirez" name="Ariel Ramirez" value="Ariel Ramirez"/>
          <label for="socios_curso_Ariel Ramirez">Ariel Ramirez</label>
          <input type="checkbox" id="socios_curso_Jorge Ibañez" name="Jorge Ibañez" value="Jorge Ibañez"/>
          <label for="socios_curso_Jorge Ibañez">Jorge Ibañez</label>
        </p>
        <p>
          La elección de cargos, en esta instancia, es solo para presidir 
          la asamblea durante el funcionamiento de la misma.
          La elección de cargos para el consejo de administración se realizará
          durante la primer reunión del consejo de administración.
        </p>
        <hr>
        <h3>03. Lectura del estatuto</h3>
        <textarea>
          ACTA CONSTITUTIVA DE LA COOPERATIVA DE TRABAJO(Consignar un nombre de fantasía)LIMITADA. - - - - -
          En (ciudad, pueblo) de (departamento, partido, etc. y provincia)
          siendo
          las (hora) horas del día (día) del mes de (mes) de (año), en el local de (sede donde se realiza la reunión) sito en la calle (calle y número) y como consecuencia de la promoción hecha anteriormente por los señores (nombre y apellido de los promotores), se reunieron, con el propósito de dejar constituida una cooperativa de trabajo, las personas que han firmado el libro de asistencia a las Asambleas
          (Solamente nombre y apellido de los asistentes al acto constitutivo. Al finalizar es conveniente insertar un salto de página, procediéndose, una vez impreso, a cerrar con una línea los espacios en blanco que quedaren.)
          La Resolución 324/94 contempla que este tipo de cooperativas puede constituirse con 6 (seis) asociados.
          Abrió el acto don (nombre y apellido de quien abre el acto) en nombre de los iniciadores, dándose lectura al Orden del Día a tratarse, y que es el siguiente: 1º) Elección de la Mesa Directiva de la Asamblea. 2º) Informe de los Iniciadores. 3º) Discusión y aprobación del estatuto. 4º) Suscripción e integración de cuotas sociales. 5º) Elección de los miembros titulares y suplentes del Consejo de Administración y de un Síndico titular y un Síndico suplente. Estos puntos fueron resueltos en la forma que se indica a continuación: 1º) ELECCION DE LA MESA DIRECTIVA DE LA ASAMBLEA: De inmediato por unanimidad los presentes designaron como Presidente y Secretario a los señores don (nombre y apellido del Presidente de la Asamblea) y don (nombre y apellido del Secretario de la Asamblea), respectivamente. 2º) INFORME DE LOS INICIADORES: En nombre de los iniciadores, don (nombre y apellido de quien realiza el informe oral) explicó el objeto de la reunión, poniendo de relieve la finalidad de la cooperativa proyectada, explicando los objetos, las bases y los métodos que son propios del sistema cooperativo y, en particular, de las entidades como la que se constituye por este acto, y los beneficios económicos, morales y culturales que ellas reportan. 3º) DISCUSION Y APROBACION DEL ESTATUTO: Terminada la exposición referida en el punto anterior, el Presidente invitó al Secretario a dar lectura del estatuto proyectado, el cual, una vez discutido, fue aprobado por unanimidad en general y en particular, en la forma que se inserta a continuación: - - - - - - - - - - - - - - - - - - - - - - -
          CAPITULO l. CONSTITUCION, DOMICILIO, DURACION Y OBJETO. ARTICULO 1º: Con la denominación de COOPERATIVA DE TRABAJO (Consignar un nombre de fantasía) LIMITADA, se constituye una cooperativa de trabajo que se regirá por las disposiciones del presenteestatuto, y en todo aquello que éste no previere, por la legislación vigente en materia de cooperativas. ARTICULO 2º: La Cooperativa tendrá su domicilio legal en (indicar con precisión la localidad, y en su caso, el Departamento o Partido y la Provincia en que la cooperativa tendrá su asiento legal.) (No se escribirá la calle y el número.).
          ARTICULO 3º: La duración de la Cooperativa es ilimitada. En caso de disolución su liquidación se hará con arreglo a lo establecido por este estatuto y la legislación cooperativa. ARTICULO 4º: La Cooperativa excluirá de todos sus actos las cuestiones políticas, religiosas, sindicales, de nacionalidad, regiones, o razas determinadas. ARTICULO 5º: La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a:
        </textarea>
        <hr>
        <h3>04. Elección de cargos</h3>
        <p>Se deben seleccionar los 3 miembros del consejo de administración y el sindico.</p>
        <h5>Elección de los miembros del Consejo de administración</h5>
        <p>
          <input type="checkbox" id="socios_curso_Ariel Federico Asus" name="Ariel Federico Asus" value="Ariel Federico Asus"/>
          <label for="socios_curso_Ariel Federico Asus">Ariel Federico Asus</label>
          <input type="checkbox" id="socios_curso_Ariel Ramirez" name="Ariel Ramirez" value="Ariel Ramirez"/>
          <label for="socios_curso_Ariel Ramirez">Ariel Ramirez</label>
          <input type="checkbox" id="socios_curso_Jorge Ibañez" name="Jorge Ibañez" value="Jorge Ibañez"/>
          <label for="socios_curso_Jorge Ibañez">Jorge Ibañez</label>
        </p>
        <h5>Elección del sindico titular</h5>
        <p>
          <input type="checkbox" id="socios_curso_Ariel Federico Asus" name="Ariel Federico Asus" value="Ariel Federico Asus"/>
          <label for="socios_curso_Ariel Federico Asus">Ariel Federico Asus</label>
          <input type="checkbox" id="socios_curso_Ariel Ramirez" name="Ariel Ramirez" value="Ariel Ramirez"/>
          <label for="socios_curso_Ariel Ramirez">Ariel Ramirez</label>
          <input type="checkbox" id="socios_curso_Jorge Ibañez" name="Jorge Ibañez" value="Jorge Ibañez"/>
          <label for="socios_curso_Jorge Ibañez">Jorge Ibañez</label>
        </p>
        <h5>Elección del sindico suplente</h5>
        <p>
          <input type="checkbox" id="socios_curso_Ariel Federico Asus" name="Ariel Federico Asus" value="Ariel Federico Asus"/>
          <label for="socios_curso_Ariel Federico Asus">Ariel Federico Asus</label>
          <input type="checkbox" id="socios_curso_Ariel Ramirez" name="Ariel Ramirez" value="Ariel Ramirez"/>
          <label for="socios_curso_Ariel Ramirez">Ariel Ramirez</label>
          <input type="checkbox" id="socios_curso_Jorge Ibañez" name="Jorge Ibañez" value="Jorge Ibañez"/>
          <label for="socios_curso_Jorge Ibañez">Jorge Ibañez</label>
        </p>
        <hr>
        <h3>05. Finalización de la asamblea</h3>
        <p>
          <label for="hora_inicio">Hora de cierre</label>
          <input type="date" id="hora_inicio" name="hora_inicio"/>
        </p>
        <button>Finalizar</button><a href="{% url 'index' %}" class="volver">volver</a>
        <h4>Estatuto y acta constitutiva</h4>
        <p><a href="#" class="descargar">Descargar estatuto</a><br>Imprimir en papel romaní o papel forense</p>
      </form>
    </div>
  </div>
</section>
{% endblock %}

mc/templates/mi_cooperativa/base.html
{% extends "base.html" %}
{% block content %}
    <section id="profile">
      {% include '_karma.html' %}
      {% block inter %}
      {% endblock %}
    </section>
{% endblock %}

mc/templates/mi_cooperativa/capital.html
{% extends "mi_cooperativa/base.html" %}
{% block inter %}
<section id="form_capital">
  <div class="content">
    <div class="help">
      <div class="box box-capital active">
        <h5>Capital social</h5>
        <h6>Capital suscripto por socio</h6><p>Se debe realizar un depósito del 5% del salario 
mínimo por cada socio.</p>
<p>Esto se puede hacer en un banco cooperativo 
como el credicoop o en cualquier banco oficial. </p>
<p><a href="http://www.inaes.com.ar">Más información</a> </p>
<p><a href="http://www.inaes.com.ar">Sucursales</a> </p>

      </div>
    </div>
    <div class="panel">
      <form action="{% url 'index' %}">
        <h3>Monto a depositár:<strong>$354,35</strong></h3>
        <p>
          <label for="fecha_deposito">Fecha de depósito</label>
          <input type="date" id="fecha_deposito" name="fecha_deposito"/>
        </p>
        <p>
          <label for="boleta">Número de boleta</label>
          <input type="text" id="boleta" name="boleta"/>
        </p>
        <p>
          <label for="banco">Banco</label>
          <input type="text" id="banco" name="banco"/>
        </p>
        <p>
          <label for="direccion_banco">Dirección</label>
          <input type="text" id="direccion_banco" name="direccion_banco"/>
        </p>
        <button>Guardar</button><a href="{% url 'index' %}" class="volver">volver</a>
      </form>
    </div>
  </div>
</section>
{% endblock %}

mc/templates/mi_cooperativa/convocatoria.html
{% extends "mi_cooperativa/base.html" %}
{% block inter %}
<section id="form_convocatoria">
  <div class="content">
    <div class="help boxes-inaes">
      <div class="box box-convocatoria active">
        <h5>Convocatoria a Asamblea</h5>
        <h6>Capital suscripto por socio</h6><p>La convocatoria debe ser 
presentada ante el inaes 15 días
antes de la realización de la asamblea</p>
<p>Para recordar a los asociados de la realización de la 
asamblea puede descargar estos afiches para imprimir 
y pegar en lugares visibles. Al menos debe estar en la 
sede de la cooperativa.</p>
<p>Recuerda que se debe comunicar por todos los 
medios posibles la realización de la asamblea.</p>
<p><a href="http://www.inaes.com.ar">Más información</a> </p>

      </div>
    </div>
    <div class="panel">
      <form action="{% url 'index' %}">
        <p>
          <label for="fecha_asamblea">Fecha de asamblea</label>
          <input type="date" id="fecha_asamblea" name="fecha_asamblea"/>
        </p>
        <p>
          <label for="direccion">Dirección</label>
          <input type="text" id="direccion" name="direccion"/>
        </p>
        <p>
          <label for="banco">Banco</label>
          <input type="text" id="banco" name="banco"/>
        </p>
        <div class="col-2">
          <p>
            <label for="direccion">Dirección</label>
            <input type="text" id="direccion" name="direccion"/>
          </p>
          <p>
            <label for="localidad">Localidad</label>
            <input type="text" id="localidad" name="localidad"/>
          </p>
        </div>
        <p>
          <input type="checkbox" id="enviar_sendmail" name="sendmail" value="sendmail"/>
          <label for="enviar_sendmail">Enviar correo electrónico a todos los socios notificando de la realización de la asamblea</label>
        </p>
        <button>Guardar</button><a href="{% url 'index' %}" class="volver">volver</a>
        <h4>Documentación de la convocatoria</h4>
        <p><a href="#" class="descargar">Descargar nota</a><br>Imprime la nota para presentar en Inaes.</p>
        <p><a href="#" class="descargar">Descargar afiche</a><br>Pegálo en la cartelera y en lugares visibles.</p>
      </form>
    </div>
  </div>
</section>
{% endblock %}

mc/templates/mi_cooperativa/crear.html
{% extends "base.html" %}

{% block content %}
<section id="profile">
  <div class="content">
    <div class="help">
        <h2>Mis cooperativas</h2>
        <p>Puedes realizar la gestión de varias cooperativas de las que formas parte.</p>
    </div>
    <div class="panel">
      <form action="{% url 'crear' %}" method="post">
        {% csrf_token %}
        <h3>Nombre comercial</h3>
        <p>"Cooperativa de trabajo"
          <input type="text" id="nombre" name="nombre" value="">"limitada".
        </p>
        <p>
          <label for="descripcion">Descripción corta</label>
          <textarea id="descripcion" name="descripcion"></textarea>
        </p>
        <button>Guardar</button><a href="{% url 'index' %}" class="volver">volver</a>
      </form>

    </div>
  </div>
</section>
{% endblock %}

mc/templates/mi_cooperativa/detail.html
{% extends "mi_cooperativa/base.html" %}
{% load tags %}
{% block inter %}

<div class="content">
  <div class="boxes">
    <div class="box box-nombre {% active_step cooperative.nombre cooperative.descripcion %}"><a href="{% url 'nombre' cooperative_id=cooperative.id %}">
        <h5>Nombre</h5>
        <p>Nombre de uso comercial.</p></a></div>
    <div class="box box-miembros {% if cooperative.partner_set.all|length > 5 %}active{% endif %}"><a href="{% url 'miembros' cooperative_id=cooperative.id %}">
        <h5>+6</h5>
        <p>Para armar una cooperativa, se necestan al menos, 6 socios.</p></a></div>
    <div class="box box-objetivo {% active_step cooperative.objeto %}"><a href="{% url 'objeto' cooperative_id=cooperative.id %}">
        <h5>Objetivo</h5>
        <p>Estar de acuerdo en que tarea van a realizar.</p></a></div>
    <div class="box box-lugar {% active_step cooperative.direccion cooperative.localidad cooperative.provincia cooperative.codigo_postal %}"><a href="{% url 'lugar' cooperative_id=cooperative.id %}">
        <h5>Lugar</h5>
        <p>Tener una sede donde funcionar.</p></a></div>

    <div class="box box-formacion"><a href="{% url 'formacion' cooperative_id=cooperative.id %}">
        <h5>Formación</h5>
        <p>Curso de cooperativismo.</p></a></div>
  </div>
  <div class="boxes-inaes">
    <div class="box box-convocatoria"><a href="{% url 'convocatoria' cooperative_id=cooperative.id %}">
        <h5>Convocatoria  a Asamblea</h5>
        <p>Genera la documantación necesaria para presentar ante el Inaes</p></a></div>
    <div class="box box-asamblea"><a href="{% url 'asamblea' cooperative_id=cooperative.id %}">
        <h5>Asamblea constitutiva</h5>
        <p>Se crea el estatuto de la cooperativa</p></a></div>
    <div class="box box-acta-consejo"><a href="{% url 'acta_consejo' cooperative_id=cooperative.id %}">
        <h5>Primer acta del consejo</h5>
        <p>Se repartin los cargos del consejo de administración</p></a></div>
    <div class="box box-capital"><a href="{% url 'capital' cooperative_id=cooperative.id %}">
        <h5>Capital social</h5>
        <p>Capital suscripto por socio.</p></a></div>
    <div class="box box-tramite"><a href="{% url 'tramite' cooperative_id=cooperative.id %}">
        <h5>Estado del tramite ante el Inaes</h5>
        <p>Información sobre la situación legal de la cooperativa</p></a></div>
  </div>
</div>
{% endblock %}

mc/templates/mi_cooperativa/formacion.html
{% extends "mi_cooperativa/base.html" %}
{% block inter %}

<section id="form_formacion">
  <div class="content">
    <div class="help">
      <div class="box box-formacion active">
        <h5>Formación</h5>
        <h6>Curso de cooperativismo.</h6><p>Todos los miembros fundadores
deben realizar el curso presencial.</p>
<p>consulta las sedes y registra la 
fecha de relización.</p>
<p><a href="http://www.inaes.com.ar">Más información</a> </p>
<p><a href="http://www.inaes.com.ar">Sedes</a> </p>

      </div>
    </div>
    <div class="panel">
      <table>
        <thead>
          <tr>
            <th>Socios</th>
            <th>Fecha del curso</th>
            <th>¿Asistió?</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Ariel Federico Asus</td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>Ariel Ramirez</td>
            <td>20.08.2014</td>
            <td>Si</td>
          </tr>
          <tr>
            <td>Jorge Ibañez</td>
            <td>20.08.2014</td>
            <td>No</td>
          </tr>
        </tbody>
      </table>
      <form action="{% url 'index' %}">
        <h3>Invitación a curso</h3>
        <p>
          <label for="fecha_asistencia">Fecha de asistencia</label>
          <input type="date" id="fecha_asistencia" name="fecha_asistencia"/>
        </p>
        <p>
          <label for="curso_sede">Sede</label>
          <input type="text" id="curso_sede" name="curso_sede"/>
        </p>
        <h4>Socios que deberán asistir</h4>
        <p>
          <input type="checkbox" id="socios_curso_Ariel Federico Asus" name="Ariel Federico Asus" value="Ariel Federico Asus"/>
          <label for="socios_curso_Ariel Federico Asus">Ariel Federico Asus</label>
          <input type="checkbox" id="socios_curso_Ariel Ramirez" name="Ariel Ramirez" value="Ariel Ramirez"/>
          <label for="socios_curso_Ariel Ramirez">Ariel Ramirez</label>
          <input type="checkbox" id="socios_curso_Jorge Ibañez" name="Jorge Ibañez" value="Jorge Ibañez"/>
          <label for="socios_curso_Jorge Ibañez">Jorge Ibañez</label>
        </p>
        <button>Agregar socio</button><a href="{% url 'index' %}" class="volver">volver</a>
      </form>
    </div>
  </div>
</section>
{% endblock %}

mc/templates/mi_cooperativa/index.html
{% extends "base.html" %}

{% block content %}
<section id="profile">
	<div class="content">
		<div class="help">
		    <h2>Mis cooperativas</h2>
		    <p>Puedes realizar la gestión de varias cooperativas de las que formas parte.</p>
		</div>
		<div class="panel">
		    {% if cooperatives %}
		        <ul class="cooperatives-list">
		        {% for cooperative in cooperatives %}
		            <li>
		            	<a href="/mi_cooperativa/{{ cooperative.id }}/">
			            	<h5>{{ cooperative.nombre }}</h5>
			            	<p>{{ cooperative.descripcion }}</p>
		            	</a>
		            </li>
		        {% endfor %}
		        </ul>
		        <p><a href="/mi_cooperativa/crear/">Crear una nueva cooperativa</a>.</p>

		    {% else %}
		        <p><a href="/mi_cooperativa/crear/">Crear mi primer cooperativa</a>.</p>
		    {% endif %}
	    </div>
	</div>
</section>
{% endblock %}